### ISSUE TITLE
bug: root detection in a nested directory inside git repo

### ISSUE THREAD

**Issue by lukekarrys** [vltpkg/vltpkg#176]
```
❯ tree -a -L2
.
├── .git
│   ├── HEAD
│   ├── config
│   ├── description
│   ├── hooks
│   ├── info
│   ├── objects
│   └── refs
└── nested
    └── package.json

7 directories, 4 files
❯ cd nested
❯ cat package.json
   1   │ {
   2   │   "dependencies": {
   3   │     "abbrev": "*"
   4   │   }
   5   │ }
❯ vlt i
file:///Users/lukekarrys/.npm-bins/node_modules/vlt/commands/install.js:38227
  const mainManifest = conf.options.packageJson.read(conf.options.projectRoot);
                                                ^

Error: Could not read package.json file
    at command (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/commands/install.js:38227:49)
    at Object.run (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:12175:15) {
  [cause]: {
    path: '/Users/lukekarrys/Desktop/scratch/vlt-root-detection/package.json',
    cause: Error: ENOENT: no such file or directory, open '/Users/lukekarrys/Desktop/scratch/vlt-root-detection/package.json'
        at readFileSync (node:fs:442:20)
        at PackageJson.read (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:219:40)
        at command (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/commands/install.js:38227:49)
        at Object.run (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:12175:15) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'open',
      path: '/Users/lukekarrys/Desktop/scratch/vlt-root-detection/package.json'
    }
  }
}

Node.js v22.4.0
```

**Comment by lukekarrys** [comment]
I don't think this is actually a bug. I had forgotten we designed root detection to use a `.git` directory as well. There is a better error message that we can show here though. I think we should make it clear:

- what directory what root was detected
- why that root was detected
- a more clear message when the root has no package.json file

**Comment by darcyclarke** [comment]
Had no clue this existed already but https://github.com/vltpkg/vltpkg/pull/251 should address this now
