### ISSUE TITLE
Rollup is not installed properly

### ISSUE THREAD

**Issue by targos** [vltpkg/vltpkg#226]
Reproduce:

```
mkdir test-rollup
cd test-rollup
npm init -y
vlt install rollup
node -e "require('rollup')"
```

```
$ vlt install rollup
node -e "require('rollup')"
/Users/mzasso/git/test/test-rollup/node_modules/.vlt/··rollup@4.24.4/node_modules/rollup/dist/native.js:63
		throw new Error(
		^

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/mzasso/git/test/test-rollup/node_modules/.vlt/··rollup@4.24.4/node_modules/rollup/dist/native.js:63:9)
    at Object.<anonymous> (/Users/mzasso/git/test/test-rollup/node_modules/.vlt/··rollup@4.24.4/node_modules/rollup/dist/native.js:72:76)
    at Module._compile (node:internal/modules/cjs/loader:1572:14)
    at Object..js (node:internal/modules/cjs/loader:1709:10)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    ... 2 lines matching cause stack trace ...
    at require (node:internal/modules/helpers:139:16) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/mzasso/git/test/test-rollup/node_modules/.vlt/··rollup@4.24.4/node_modules/rollup/dist/native.js
  - /Users/mzasso/git/test/test-rollup/node_modules/.vlt/··rollup@4.24.4/node_modules/rollup/dist/shared/parseAst.js
  - /Users/mzasso/git/test/test-rollup/node_modules/.vlt/··rollup@4.24.4/node_modules/rollup/dist/shared/rollup.js
  - /Users/mzasso/git/test/test-rollup/node_modules/.vlt/··rollup@4.24.4/node_modules/rollup/dist/rollup.js
  - /Users/mzasso/git/test/test-rollup/[eval]
```

/cc @ruyadorno

**Comment by lukekarrys** [comment]
Linking to https://github.com/vltpkg/vltpkg/issues/162 since they seem very similar.
