### ISSUE TITLE
[BUG] Sending HTTP request to HTTPS port when behind proxy

### ISSUE THREAD

**Issue by lishaduck** [vltpkg/vltpkg#249]
Morning! err... I guess it's afternoon now.
The first `vlt install` I've attempted failed rather loudly.

```error
Error: failed to fetch packument
    at PackageInfoClient.packument (file:///Users/dukese01/Library/Caches/deno/npm/registry.npmjs.org/vlt/0.0.0-0.1730830331789/vlt.js:55417:39)
    at Object.runMicrotasks (ext:core/01_core.js:683:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:182:21)
    at async PackageInfoClient.manifest (file:///Users/dukese01/Library/Caches/deno/npm/registry.npmjs.org/vlt/0.0.0-0.1730830331789/vlt.js:55312:39)
    at async file:///Users/dukese01/Library/Caches/deno/npm/registry.npmjs.org/vlt/0.0.0-0.1730830331789/vlt.js:16747:22
    at async Promise.all (index 33)
    at async appendNodes (file:///Users/dukese01/Library/Caches/deno/npm/registry.npmjs.org/vlt/0.0.0-0.1730830331789/vlt.js:16739:7)
    at async addNodes (file:///Users/dukese01/Library/Caches/deno/npm/registry.npmjs.org/vlt/0.0.0-0.1730830331789/vlt.js:16826:9)
Caused by {
  code: ERESOLVE,
  spec: @vltpkg/spec.Spec {
    type: 'registry',
    spec: 'elm-review@^2.12.0',
    name: 'elm-review',
    bareSpec: '^2.12.0',
    registry: 'https://registry.npmjs.org/',
    registrySpec: '^2.12.0',
    semver: '^2.12.0',
    range: Range {
      raw: '^2.12.0',
      isAny: false,
      isSingle: false,
      set: [
        Comparator {
          includePrerelease: false,
          raw: '^2.12.0',
          tokens: [ '^2.12.0' ],
          tuples: [ [Array], [Array] ],
          isNone: false,
          isAny: false
        }
      ],
      includePrerelease: false
    }
  },
  from: /Users/dukese01/Developer/elm-pages,
  url: URL {
    href: https://registry.npmjs.org/elm-review,
    origin: https://registry.npmjs.org,
    protocol: https:,
    username: ,
    password: ,
    host: registry.npmjs.org,
    hostname: registry.npmjs.org,
    port: ,
    pathname: /elm-review,
    hash: ,
    search: 
  },
  response: @vltpkg/registry-client.CacheEntry {
    statusCode: 400,
    headers: [
      [ 'server', 'cloudflare' ],
      [ 'date', 'Tue, 26 Nov 2024 18:04:24 GMT' ],
      [ 'content-type', 'text/html' ],
      [ 'content-length', '253' ],
      [ 'connection', 'close' ],
      [ 'cf-ray', '-' ]
    ],
    text: '<html>\r\n' +
      '<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>400 Bad Request</h1></center>\r\n' +
      '<center>The plain HTTP request was sent to HTTPS port</center>\r\n' +
      '<hr><center>cloudflare</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
  }
}
```

I'd guess that it's probably something about my setup?
I've installed `vlt` using Deno, but an installing an existing Node.js npm project with a `package-lock.json` (but no `node_modules` yet). I'm behind a proxy, but curl, etc works (only gui apps are affected, don't ask me how 🤷‍♂)—pnpm, deno, and npm work, haven't used yarn or bun in a couple years, but they worked too.

---

P.S. Loving the GUI! (for pnpm projects, I obviously haven't gotten a vlt install to work, and npm installs aren't getting picked up)

**Comment by isaacs** [comment]
What can you tell me about this proxy you're behind? I'm willing to bet that's the issue, because it seems like it's sending an unencrypted HTTP request to an HTTPS port (443). Since other things work, I'm assuming there's something vlt is doing wrong.

**Comment by lishaduck** [comment]
> What can you tell me about this proxy you're behind? I'm willing to bet that's the issue, because it seems like it's sending an unencrypted HTTP request to an HTTPS port (443). Since other things work, I'm assuming there's something vlt is doing wrong.

Hmm... I can ask the IT department. What specifically would you need to know?
I'm a student, FERPA mandates schools have web filters. Our school uses a two-tiered system, one level applies macOS profiles to Chrome and Safari that force using a specific DNS resolver that redirects problematic websites, and it also alters some certificates (device level). The second level alters IPs sent over the network to redirect `8.8.8.8`, `1.1.1.1`, etc, to the custom DNS resolver to prevent BYOD devices from bypassing the system, and blocks direct access to Reddit (probably other things, but that's what I've noticed).
The browser-based DNS resolver breaks `npmjs.org`, but the server-based filter lets it through, so `pnpm` and `npm` still work, both at school and at home.

**Comment by darcyclarke** [comment]
@lishaduck is this still an issue? If so, could you potentially share what an `npm config get` returns & maybe an example of a `npm` `package-lock.json` file generated for your actual &/or a test project.

**Comment by lishaduck** [comment]
> [@lishaduck](https://github.com/lishaduck) is this still an issue? If so, could you potentially share what an `npm config get` returns & maybe an example of a `npm` `package-lock.json` file generated for your actual &/or a test project.

Funnily enough, I was just checking an hour or two ago.

```
; node bin location = /Users/dukese01/.nvm/versions/node/v23.6.0/bin/node
; node version = v23.6.0
; npm local prefix = /Users/dukese01/Developer/node-elm-review
; npm version = 10.9.2
; cwd = /Users/dukese01/Developer/node-elm-review
; HOME = /Users/dukese01
; Run `npm config ls -l` to show all defaults.
```

New stacktrace: 

```
 rm -rf package-lock.json node_modules && npx vlt@latest install
build ⠋ > actual ✓ > reify
50 requests
Error: failed to fetch packument
    at PackageInfoClient.packument (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:65171:35)
    at async PackageInfoClient.manifest (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:65066:35)
    at async file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:53507:18
    at async Promise.all (index 17)
    at async appendNodes (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:53499:3)
    at async addNodes (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:53590:5)
    at async buildIdealFromStartingGraph (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:53625:3)
    at async Object.build (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:53654:15)
    at async install (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:65296:17)
    at async command (file:///Users/dukese01/.npm/_npx/392bc572a0869a7c/node_modules/vlt/commands/install.js:69995:21) {
  [cause]: {
    code: 'ERESOLVE',
    spec: @vltpkg/spec.Spec {
      type: 'registry',
      spec: 'which@^2.0.2',
      name: 'which',
      bareSpec: '^2.0.2',
      registry: 'https://registry.npmjs.org/',
      registrySpec: '^2.0.2',
      semver: '^2.0.2',
      range: Range {
        raw: '^2.0.2',
        isAny: false,
        isSingle: false,
        set: [ [Comparator] ],
        includePrerelease: false
      }
    },
    from: '/Users/dukese01/Developer/node-elm-review',
    url: URL {
      href: 'https://registry.npmjs.org/which',
      origin: 'https://registry.npmjs.org',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'registry.npmjs.org',
      hostname: 'registry.npmjs.org',
      port: '',
      pathname: '/which',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    response: @vltpkg/registry-client.CacheEntry {
      statusCode: 400,
      headers: [
        [ 'server', 'cloudflare' ],
        [ 'date', 'Tue, 26 Nov 2024 18:04:24 GMT' ],
        [ 'content-type', 'text/html' ],
        [ 'content-length', '253' ],
        [ 'connection', 'close' ],
        [ 'cf-ray', '-' ]
      ],
      text: '<html>\r\n' +
        '<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n' +
        '<body>\r\n' +
        '<center><h1>400 Bad Request</h1></center>\r\n' +
        '<center>The plain HTTP request was sent to HTTPS port</center>\r\n' +
        '<hr><center>cloudflare</center>\r\n' +
        '</body>\r\n' +
        '</html>\r\n'
    }
  }
}
```

Running in this project: https://github.com/lishaduck/node-elm-review/blob/main/package-lock.json
