### ISSUE TITLE
[BUG] `ERESOLVE` when installing `tailwindcss-animate`

### ISSUE THREAD

**Issue by lukekarrys** [vltpkg/vltpkg#260]
**package.json**
```
{
  "name": "vlt-install-stuff",
  "version": "1.0.0",
  "dependencies": {
    "tailwindcss-animate": "^1.0.7"
  }
}
```

```
❯ vlt i
Error: Could not resolve
    at PackageInfoClient.manifest (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:55314:39)
    at async file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:16747:22
    at async Promise.all (index 0)
    at async appendNodes (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:16739:7)
    at async Promise.all (index 0)
    at async file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:16800:9
    at async Promise.all (index 0)
    at async appendNodes (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:16739:7)
    at async addNodes (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:16826:9)
    at async buildIdealFromStartingGraph (file:///Users/lukekarrys/.npm-bins/node_modules/vlt/vlt.js:16864:7) {
  [cause]: {
    code: 'ERESOLVE',
    spec: @vltpkg/spec.Spec {
      type: 'registry',
      spec: 'tailwindcss@>=3.0.0 || insiders',
      name: 'tailwindcss',
      bareSpec: '>=3.0.0 || insiders',
      registry: 'https://registry.npmjs.org/',
      registrySpec: '>=3.0.0 || insiders',
      distTag: '>=3.0.0 || insiders'
    },
    from: '/Users/lukekarrys/Desktop/scratch/vlt-install-stuff/node_modules/.vlt/··tailwindcss-animate@1.0.7/node_modules/tailwindcss-animate'
  }
}
```

**Comment by lukekarrys** [comment]
Closing in favor of #273 which found the actual big that caused this.
