### ISSUE TITLE
[BUG] process stalls between command finish and `process.exit`

### ISSUE THREAD

**Issue by lukekarrys** [vltpkg/vltpkg#261]
With the following changes to the vlt bin, I was measuring the time between the command finishing and `process.exit` being run.

When running `vlt i` and one of the deps fails to resolve, a bunch of active fs requests are left hanging which take time to clean up.

```patch
diff --git a/src/vlt/src/bins/vlt.ts b/src/vlt/src/bins/vlt.ts
index c9f614c2..53227b5b 100644
--- a/src/vlt/src/bins/vlt.ts
+++ b/src/vlt/src/bins/vlt.ts
@@ -1,2 +1,12 @@
 #!/usr/bin/env node
-void import('../index.js').then(r => r.default())
+let time = 0
+process.on('exit', () => {
+  console.log(`before exit ${Date.now() - time}ms`)
+})
+await import('../index.js')
+  .then(r => r.default())
+  .then(() => {
+    console.log('really really done!')
+    time = Date.now()
+    console.log((process as any)._getActiveRequests())
+  })
```

Here's an example of running with those changes on this package.json:

```json
  "dependencies": {
    "@astrojs/check": "^0.9.4",
    "@astrojs/mdx": "^3.1.9",
    "@astrojs/react": "^3.6.3",
    "@astrojs/starlight": "^0.29.2",
    "@astrojs/tailwind": "^5.1.3",
    "@astrojs/vercel": "^7.8.2",
    "@fontsource-variable/manrope": "^5.1.0",
    "@radix-ui/react-dialog": "^1.1.2",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.3",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.1",
    "astro": "^4.16.17",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "gray-matter": "^4.0.3",
    "lucide-react": "^0.453.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "sharp": "^0.33.5",
    "tailwind-merge": "^2.5.2",
    "tailwindcss": "^3.4.14",
    "tailwindcss-animate": "^1.0.7",
    "typedoc": "^0.27.4",
    "typedoc-plugin-frontmatter": "^1.1.0",
    "typedoc-plugin-markdown": "^4.3.2",
    "typedoc-plugin-remark": "^1.2.0",
    "vite": "^5.4.11"
  }
```

```
❯ vlt_local i
Error: Could not resolve
    at PackageInfoClient.manifest (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/package-info/dist/esm/index.js:267:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/dist/esm/ideal/append-nodes.js:52:22
    at async Promise.all (index 0)
    at async appendNodes (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/dist/esm/ideal/append-nodes.js:43:5)
    at async Promise.all (index 0)
    at async file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/dist/esm/ideal/append-nodes.js:139:9
    at async Promise.all (index 24)
    at async appendNodes (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/dist/esm/ideal/append-nodes.js:43:5)
    at async addNodes (file:///Users/lukekarrys/projects/vltpkg/vltpkg/src/graph/dist/esm/ideal/add-nodes.js:25:9) {
  [cause]: {
    code: 'ERESOLVE',
    spec: @vltpkg/spec.Spec {
      type: 'registry',
      spec: 'tailwindcss@>=3.0.0 || insiders',
      name: 'tailwindcss',
      bareSpec: '>=3.0.0 || insiders',
      registry: 'https://registry.npmjs.org/',
      registrySpec: '>=3.0.0 || insiders',
      distTag: '>=3.0.0 || insiders'
    },
    from: '/Users/lukekarrys/Desktop/scratch/vlt-install-stuff/node_modules/.vlt/··tailwindcss-animate@1.0.7/node_modules/tailwindcss-animate'
  }
}
really really done!
[
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FileHandleCloseReq {},
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FileHandleCloseReq {},
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } },
  FSReqPromise { promise: Promise { <pending> } }
]
before exit 5620ms
```

**Comment by darcyclarke** [comment]
@isaacs is this something you could look into & see if it's still happening/how to address if it is?

**Comment by isaacs** [comment]
I will take a look at it.
